spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          gitlab-ce:
            client-id: 3dd507c3a8c1b6dc3b66def35d410d7d03344ed891e5a53529a0605f6699261a 
            client-secret: gloas-80bed3352c8702c1b63b4705f4f583e02ff40865923031c4d7dd5fea9e47ed55
            scope: openid+profile+email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/gitlab-ce"
        provider:
          gitlab-ce:
            issuer-uri: https://git-ce.rwth-aachen.de
            user-name-attribute: sub



server:
  port: 8080
